config/routes.rb
Website::Application.routes.draw do

  resources :meetings

  resources :cigs_per_days
  
  resources :family do
     collection do
      get "instructions"
      get "movements"
    end
   end
  resources :sensor_data
  resources :sleep_data
  resources :panic_alarms
  resources :sw_diaries
  resources :health_data
  resources :gps_data
  resources :gp_diagnoses

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root :to=> 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    :to => 'static_pages#help'
  match '/about',   :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'

end

app/models/cigs_per_day.rb
class CigsPerDay < ActiveRecord::Base
  attr_accessible :no_of_cigs
end

app/models/gp_diagnosis.rb
class GpDiagnosis < ActiveRecord::Base
  attr_accessible :diagnosis
end

app/models/gps_data.rb
class GpsData < ActiveRecord::Base
  attr_accessible :lat, :lng, :time
end

app/models/health_datum.rb
class HealthDatum < ActiveRecord::Base
  attr_accessible :blood_pressure, :cigs_per_day, :coughs_per_day, :height, :respitory_rate, :weight
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :date, :notes, :requested_by, :response, :time, :with
end

app/models/panic_alarm.rb
class PanicAlarm < ActiveRecord::Base
  attr_accessible :activated
end

app/models/right.rb
class Right < ActiveRecord::Base
	has_and_belongs_to_many :roles
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_and_belongs_to_many :rights
end

app/models/sensor_data.rb
class SensorData < ActiveRecord::Base
  attr_accessible :sensor, :sensor_name, :state, :time
end

app/models/sleep_data.rb
class SleepData < ActiveRecord::Base
  attr_accessible :end_time, :mood, :notes, :sleepquality, :start_time, :timeinbed
end

app/models/sw_diary.rb
class SwDiary < ActiveRecord::Base
  attr_accessible :diary
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_and_belongs_to_many :roles

  has_secure_password

  before_save {|user| user.email = email.downcase}
  before_save :create_remember_token
  
  validates :name, :presence=> true, :length=> { :maximum=> 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence=> true, 
  					:format=> { :with=> VALID_EMAIL_REGEX }, 
  					:uniqueness=> { :case_sensitive=> false }
  validates :password, :length=>{:minimum=>6}
  validates :password_confirmation, :presence=>true

private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/static_p_ages_controller.rb
class StaticPAgesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

skip_before_filter  :check_authorization

def home
	@Health_Data = HealthDatum.last
	@panic_alarm = PanicAlarm.new
	@gp_diagnosis = GpDiagnosis.last

	if current_user.blank?
		redirect_to new_session_path
	end
end

def help
end

def about
end

def contact
end

end

app/helpers/application_helper.rb
module ApplicationHelper
	include Mobvious::Rails::Helper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/family_helper.rb
module FamilyHelper
end

app/helpers/gps_data_helper.rb
module GpsDataHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/sleep_data_helper.rb
module SleepDataHelper
end

app/helpers/static_p_ages_helper.rb
module StaticPAgesHelper
end

app/helpers/sw_diaries_helper.rb
module SwDiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/static_p_ages/help.html.erb
<h1>StaticPAges#help</h1>
<p>Find me in app/views/static_p_ages/help.html.erb</p>

app/views/static_p_ages/home.html.erb
<h1>StaticPAges#home</h1>
<p>Find me in app/views/static_p_ages/home.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<p> Name: <%= current_user.name%> </p>
<p> Stakeholder Type: <%= current_user.roles.first.name %> </p>

<div class="center hero-unit">
  <h1>Home</h1>




<%= link_to "Sleep Data", sleep_data_path, :class=> "btn btn-large btn-primary" %></br></br>
<%= link_to "Request Meeting", new_meeting_path, :class=> "btn btn-large btn-primary" %></br></br>
<%= link_to "View Meeting Requests", meetings_path, :class=> "btn btn-large btn-primary" %></br></br>

<%if current_user.roles.first.name != "Family" %>
<%= link_to "Health Data", @Health_Data, :class=> "btn btn-large btn-primary" %></br></br>
<%= link_to "Movement Outside The Home", gps_data_path, :class=> "btn btn-large btn-primary" %></br></br>
<%= link_to "Movement Within The Home", sensor_data_path, :class=> "btn btn-large btn-primary" %></br></br>
<%end%>

<%if current_user.roles.first.name == "Patient" %>

<%= form_for(@panic_alarm) do |f| %>
	<div class="field">
    	<%= f.hidden_field :activated, :value =>'true' %>
  	</div>
  	<div class="actions">
    	<%= f.submit "Panic Alarm", :class => "btn btn-large btn-primary"   %>
  	</div>
<% end %>
<%= link_to "Input Number of Cigarettes Today", new_cigs_per_day_path, :class=> "btn btn-large btn-primary" %></br></br>
<%end%>

<%if current_user.roles.first.name == "Family" %>

<%= link_to "Panic Alarm History", panic_alarms_path, :class=> "btn btn-large btn-primary" %></br></br>
<%= link_to "View Health Data and Notes", instructions_family_index_path, :class=> "btn btn-large btn-primary" %></br></br>

<%= link_to "View Movements", movements_family_index_path, :class=> "btn btn-large btn-primary" %></br></br>
<% end%>

<%if current_user.roles.first.name == "Social Worker" %>

<%= link_to "View GP Diagnosis", @gp_diagnosis, :class=> "btn btn-large btn-primary" %></br></br>
<%= link_to "Write Diary", new_sw_diary_path, :class=> "btn btn-large btn-primary" %></br></br>
<%end%>

<%if current_user.roles.first.name == "GP" %>

<%= link_to "Write Diagnosis", new_gp_diagnosis_path, :class=> "btn btn-large btn-primary" %></br></br>
<%end%>

</div>

app/views/static_pages/home.mobile.html.erb
This is the mobile homepage