config/routes.rb
Website::Application.routes.draw do

  resources :meetings

  resources :cigs_per_days
  
  resources :family do
     collection do
      get "instructions"
      get "movements"
    end
   end
  resources :sensor_data
  resources :sleep_data
  resources :panic_alarms
  resources :sw_diaries
  resources :health_data
  resources :gps_data
  resources :gp_diagnoses

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root :to=> 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    :to => 'static_pages#help'
  match '/about',   :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'

end

app/models/cigs_per_day.rb
class CigsPerDay < ActiveRecord::Base
  attr_accessible :no_of_cigs
end

app/models/gp_diagnosis.rb
class GpDiagnosis < ActiveRecord::Base
  attr_accessible :diagnosis
end

app/models/gps_data.rb
class GpsData < ActiveRecord::Base
  attr_accessible :lat, :lng, :time
end

app/models/health_datum.rb
class HealthDatum < ActiveRecord::Base
  attr_accessible :blood_pressure, :cigs_per_day, :coughs_per_day, :height, :respitory_rate, :weight
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :date, :notes, :requested_by, :response, :time, :with
end

app/models/panic_alarm.rb
class PanicAlarm < ActiveRecord::Base
  attr_accessible :activated
end

app/models/right.rb
class Right < ActiveRecord::Base
	has_and_belongs_to_many :roles
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_and_belongs_to_many :rights
end

app/models/sensor_data.rb
class SensorData < ActiveRecord::Base
  attr_accessible :sensor, :sensor_name, :state, :time
end

app/models/sleep_data.rb
class SleepData < ActiveRecord::Base
  attr_accessible :end_time, :mood, :notes, :sleepquality, :start_time, :timeinbed
end

app/models/sw_diary.rb
class SwDiary < ActiveRecord::Base
  attr_accessible :diary
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_and_belongs_to_many :roles

  has_secure_password

  before_save {|user| user.email = email.downcase}
  before_save :create_remember_token
  
  validates :name, :presence=> true, :length=> { :maximum=> 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence=> true, 
  					:format=> { :with=> VALID_EMAIL_REGEX }, 
  					:uniqueness=> { :case_sensitive=> false }
  validates :password, :length=>{:minimum=>6}
  validates :password_confirmation, :presence=>true

private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/panic_alarms_controller.rb
class PanicAlarmsController < ApplicationController
  # GET /panic_alarms
  # GET /panic_alarms.json
  def index
    @panic_alarms = PanicAlarm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @panic_alarms }
    end
  end

  # GET /panic_alarms/1
  # GET /panic_alarms/1.json
  def show
    @panic_alarm = PanicAlarm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @panic_alarm }
    end
  end

  # GET /panic_alarms/new
  # GET /panic_alarms/new.json
  def new
    @panic_alarm = PanicAlarm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @panic_alarm }
    end
  end

  # POST /panic_alarms
  # POST /panic_alarms.json
  def create
    @panic_alarm = PanicAlarm.new(params[:panic_alarm])

    respond_to do |format|
      if @panic_alarm.save
        format.html { redirect_to root_path, notice: 'Panic Alarm was Activated' }
        format.json { render json: root_path, status: :created, location: @panic_alarm }
      else
        format.html { render action: "new" }
        format.json { render json: @panic_alarm.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	include Mobvious::Rails::Helper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/family_helper.rb
module FamilyHelper
end

app/helpers/gps_data_helper.rb
module GpsDataHelper
end

app/helpers/health_data_helper.rb
module HealthDataHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/panic_alarms_helper.rb
module PanicAlarmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/sleep_data_helper.rb
module SleepDataHelper
end

app/helpers/sw_diaries_helper.rb
module SwDiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/panic_alarms/_form.html.erb
<%= form_for(@panic_alarm) do |f| %>
  <% if @panic_alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@panic_alarm.errors.count, "error") %> prohibited this panic_alarm from being saved:</h2>

      <ul>
      <% @panic_alarm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activated %><br />
    <%= f.check_box :activated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/panic_alarms/index.html.erb
<h1>Panic Alarm History</h1>
<p> Uses of the panic alarm in the last week are highlighted in yellow </p>

<table class = "table">
  <tr>
    <th>Date</th>
    <th>Time</th>
  </tr>

<% @panic_alarms.each do |panic_alarm| %>
<% if panic_alarm.activated == true %>
  <tr<% if Time.now - panic_alarm.created_at < 604800 %> style="background-color: yellow;" <%end%>>
    <td ><%= panic_alarm.created_at.to_date.strftime("%d/%m/%Y") %></td>
    <td><%= panic_alarm.created_at.strftime('%H:%M:%S') %></td>
  </tr>
  <% end %>
<% end %>
</table>



<br />

app/views/panic_alarms/new.html.erb
<h1>New panic_alarm</h1>

<%= render 'form' %>

<%= link_to 'Back', panic_alarms_path %>

app/views/panic_alarms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Activated:</b>
  <%= @panic_alarm.activated %>
</p>





<%= link_to 'Edit', edit_panic_alarm_path(@panic_alarm) %> |
<%= link_to 'Back', panic_alarms_path %>