config/routes.rb
Website::Application.routes.draw do

  resources :meetings

  resources :cigs_per_days
  
  resources :family do
     collection do
      get "instructions"
      get "movements"
    end
   end
  resources :sensor_data
  resources :sleep_data
  resources :panic_alarms
  resources :sw_diaries
  resources :health_data
  resources :gps_data
  resources :gp_diagnoses

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root :to=> 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    :to => 'static_pages#help'
  match '/about',   :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'

end

app/models/cigs_per_day.rb
class CigsPerDay < ActiveRecord::Base
  attr_accessible :no_of_cigs
end

app/models/gp_diagnosis.rb
class GpDiagnosis < ActiveRecord::Base
  attr_accessible :diagnosis
end

app/models/gps_data.rb
class GpsData < ActiveRecord::Base
  attr_accessible :lat, :lng, :time
end

app/models/health_datum.rb
class HealthDatum < ActiveRecord::Base
  attr_accessible :blood_pressure, :cigs_per_day, :coughs_per_day, :height, :respitory_rate, :weight
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :date, :notes, :requested_by, :response, :time, :with
end

app/models/panic_alarm.rb
class PanicAlarm < ActiveRecord::Base
  attr_accessible :activated
end

app/models/right.rb
class Right < ActiveRecord::Base
	has_and_belongs_to_many :roles
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_and_belongs_to_many :rights
end

app/models/sensor_data.rb
class SensorData < ActiveRecord::Base
  attr_accessible :sensor, :sensor_name, :state, :time
end

app/models/sleep_data.rb
class SleepData < ActiveRecord::Base
  attr_accessible :end_time, :mood, :notes, :sleepquality, :start_time, :timeinbed
end

app/models/sw_diary.rb
class SwDiary < ActiveRecord::Base
  attr_accessible :diary
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_and_belongs_to_many :roles

  has_secure_password

  before_save {|user| user.email = email.downcase}
  before_save :create_remember_token
  
  validates :name, :presence=> true, :length=> { :maximum=> 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence=> true, 
  					:format=> { :with=> VALID_EMAIL_REGEX }, 
  					:uniqueness=> { :case_sensitive=> false }
  validates :password, :length=>{:minimum=>6}
  validates :password_confirmation, :presence=>true

private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings_with = Meeting.find(:all, :conditions => ["with == ?", current_user.id])
    @meetings_requested = Meeting.find(:all, :conditions => ["requested_by == ?", current_user.id])
    @users = User.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    @users = User.find(:all, :conditions => ["id != ?", current_user.id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include Mobvious::Rails::Helper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/family_helper.rb
module FamilyHelper
end

app/helpers/gps_data_helper.rb
module GpsDataHelper
end

app/helpers/health_data_helper.rb
module HealthDataHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/sensor_data_helper.rb
module SensorDataHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/sleep_data_helper.rb
module SleepDataHelper
end

app/helpers/sw_diaries_helper.rb
module SwDiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requested_by %><br />
    <%= f.number_field :requested_by %>
  </div>
  <div class="field">
    <%= f.label :with %><br />
    <%= f.number_field :with %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :response %><br />
    <%= f.check_box :response %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Respond to Meeting Request</h1>

<p> You're current respone to this meeting is: 
	<% if @meeting.response == true %>
		</br></br><%= "I can make it" %>
	<%elsif @meeting.response == false %>
		</br></br><%= "I can't make it" %>
	<%else %>
		</br></br><%= "Not responded" %>
	<%end%>
</br></br>Please tick the box below if you can make this meeting </p>
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.check_box :response %>
  </div>
  </br>
  <div class="actions">
    <%= f.submit "Respond", :class=> "btn btn-large btn-primary"  %>
  </div>
<% end %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1>Meeting Requests</h1>

<h2> Meeting Requests Recieved</h2>

<table class = "table">
  <tr>
    <th>Requested By</th>
    <th>Date</th>
    <th>Time</th>
    <th>Response</th>
    <th></th>
    <th></th>
  </tr>

<% @meetings_with.each do |meeting| %>

  <tr>
     <td><% @users.each do |u| %>
        <% if u.id == meeting.requested_by%>
            <%= u.name %>
            <%end%>
        <%end%>
    </td>
    <td><%= meeting.date %></td>
    <td><%= meeting.time.strftime('%H:%M') %></td>
    <td><% if meeting.response == true %>
        <%= "I can make it" %>
    <%elsif meeting.response == false %>
        <%="I can't make it" %>
    <%else %>
        <%="Not responded" %>
    <%end%></td>
    <td><%= link_to 'View Request', meeting, :class=> "btn btn-small btn-primary"  %></td>
    <td><%= link_to 'Respond', edit_meeting_path(meeting), :class=> "btn btn-small btn-primary"  %></td>
  </tr>
<% end %>
</table>

<h2> Meeting Requests Sent </h2>
<table class = "table">
  <tr>
    <th>With</th>
    <th>Date</th>
    <th>Time</th>
    <th>Response</th>
    <th></th>
  </tr>

<% @meetings_requested.each do |meeting| %>
  <tr>
    <td><% @users.each do |u| %>
        <% if u.id == meeting.with%>
            <%= u.name %>
            <%end%>
        <%end%>
    </td>
    <td><%= meeting.date %></td>
    <td><%= meeting.time.strftime('%H:%M') %></td>
    <td><% if meeting.response == true %>
        <%= "I can make it" %>
    <%elsif meeting.response == false %>
        <%="I can't make it" %>
    <%else %>
        <%="Not responded" %>
    <%end%></td>
    <td><%= link_to 'View Request', meeting, :class=> "btn btn-small btn-primary"  %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>Request a Meeting</h1>

<div class="row">
      <%= form_for(@meeting) do |f| %>
        <% if @meeting.errors.any? %>
          <div id="error_explanation">
          <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
          <ul>
          <% @meeting.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.hidden_field :requested_by, :value => current_user.id %>
        </div>
        <div class="field">
          <%= f.label :with, "With:" %><br />
          <%=f.collection_select :with, @users, :id, :name%>
        </div>
        <div class="field">
          <%= f.label :date, "Date:" %><br />
          <%= f.date_select :date, :order => [:day, :month, :year] %>
        </div>
        <div class="field">
          <%= f.label :time, "Time:" %><br />
          <%= f.time_select :time %>
        </div>

        <div class="field">
          <%= f.label :notes, "Notes: " %><br />
          <%= f.text_area :notes %>
        </div>
        <div class="actions">
          <%= f.submit "Request Meeting", :class=> "btn btn-large btn-primary" %>
        </div>
    <% end %>

    <%= link_to 'Back', meetings_path, :class=> "btn btn-large btn-primary" %>
</div>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Requested by:</b>
  <%= @meeting.requested_by %>
</p>

<p>
  <b>With:</b>
  <%= @meeting.with %>
</p>

<p>
  <b>Date:</b>
  <%= @meeting.date %>
</p>

<p>
  <b>Time:</b>
  <%= @meeting.time %>
</p>

<p>
  <b>Response:</b>
  <%= @meeting.response %>
</p>

<p>
  <b>Notes:</b>
  <%= @meeting.notes %>
</p>


<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>